//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigSms
    {
        public long Id { get; set; }
        public int Type { get; set; }
        public Nullable<int> Source { get; set; }
        public string Mobile { get; set; }
        public string SmsContent { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusTime { get; set; }
        public string SendMsg { get; set; }
        public bool IsTimer { get; set; }
        public Nullable<System.DateTime> Timing { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
