//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigMsgTemplate
    {
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public bool SmsIsEnable { get; set; }
        public string SMSContent { get; set; }
        public bool EmailIsEnable { get; set; }
        public string EmailTitle { get; set; }
        public string EmailContent { get; set; }
        public bool MsgIsEnable { get; set; }
        public string MsgTitle { get; set; }
        public string MsgContent { get; set; }
        public string TagIds { get; set; }
    }
}
