//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigFiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigFiles()
        {
            this.GoodsInfo_Picture = new HashSet<GoodsInfo_Picture>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Directory { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int Type { get; set; }
        public string MimeType { get; set; }
        public string Tag { get; set; }
        public string Size { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfo_Picture> GoodsInfo_Picture { get; set; }
    }
}
