//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizeUserInfo
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public int Waist { get; set; }
        public int Arm { get; set; }
        public Nullable<int> Bust { get; set; }
        public string BackPhoto { get; set; }
        public string SidePhoto { get; set; }
        public Nullable<int> Accustome { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
