//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizeStyleItem
    {
        public int Id { get; set; }
        public int StyleId { get; set; }
        public Nullable<int> CodeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Diagram { get; set; }
        public int DisplayOrder { get; set; }
        public string Description { get; set; }
    
        public virtual CustomizeStyle CustomizeStyle { get; set; }
    }
}
