//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizeModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CustomizeType { get; set; }
        public Nullable<int> SuitType { get; set; }
        public int ProduceDays { get; set; }
        public string Data { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int FabricUseCount { get; set; }
    }
}
