//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ECS.DataBase
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ConfigAll> ConfigAll
        {
            get
            {
                if ((_ConfigAll == null))
                {
                    _ConfigAll = base.CreateObjectSet<ConfigAll>("ConfigAll");
                }
                return _ConfigAll;
            }
        }
        private ObjectSet<ConfigAll> _ConfigAll;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ConfigArea> ConfigArea
        {
            get
            {
                if ((_ConfigArea == null))
                {
                    _ConfigArea = base.CreateObjectSet<ConfigArea>("ConfigArea");
                }
                return _ConfigArea;
            }
        }
        private ObjectSet<ConfigArea> _ConfigArea;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 ConfigAll EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToConfigAll(ConfigAll configAll)
        {
            base.AddObject("ConfigAll", configAll);
        }
    
        /// <summary>
        /// 用于向 ConfigArea EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToConfigArea(ConfigArea configArea)
        {
            base.AddObject("ConfigArea", configArea);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECS.HOMEI.MGModel", Name="ConfigAll")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigAll : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ConfigAll 对象。
        /// </summary>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="value">Value 属性的初始值。</param>
        public static ConfigAll CreateConfigAll(global::System.String name, global::System.String value)
        {
            ConfigAll configAll = new ConfigAll();
            configAll.Name = name;
            configAll.Value = value;
            return configAll;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECS.HOMEI.MGModel", Name="ConfigArea")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigArea : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ConfigArea 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="provinceId">ProvinceId 属性的初始值。</param>
        /// <param name="cityId">CityId 属性的初始值。</param>
        /// <param name="isCashOnDelivery">IsCashOnDelivery 属性的初始值。</param>
        /// <param name="isEnable">IsEnable 属性的初始值。</param>
        /// <param name="displayOrder">DisplayOrder 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="lastUpdateTime">LastUpdateTime 属性的初始值。</param>
        public static ConfigArea CreateConfigArea(global::System.Int32 id, global::System.String name, global::System.Int32 provinceId, global::System.Int32 cityId, global::System.Boolean isCashOnDelivery, global::System.Boolean isEnable, global::System.Int32 displayOrder, global::System.DateTime createTime, global::System.DateTime lastUpdateTime)
        {
            ConfigArea configArea = new ConfigArea();
            configArea.Id = id;
            configArea.Name = name;
            configArea.ProvinceId = provinceId;
            configArea.CityId = cityId;
            configArea.IsCashOnDelivery = isCashOnDelivery;
            configArea.IsEnable = isEnable;
            configArea.DisplayOrder = displayOrder;
            configArea.CreateTime = createTime;
            configArea.LastUpdateTime = lastUpdateTime;
            return configArea;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProvinceId
        {
            get
            {
                return _ProvinceId;
            }
            set
            {
                OnProvinceIdChanging(value);
                ReportPropertyChanging("ProvinceId");
                _ProvinceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProvinceId");
                OnProvinceIdChanged();
            }
        }
        private global::System.Int32 _ProvinceId;
        partial void OnProvinceIdChanging(global::System.Int32 value);
        partial void OnProvinceIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                OnCityIdChanging(value);
                ReportPropertyChanging("CityId");
                _CityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityId");
                OnCityIdChanged();
            }
        }
        private global::System.Int32 _CityId;
        partial void OnCityIdChanging(global::System.Int32 value);
        partial void OnCityIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaCode
        {
            get
            {
                return _AreaCode;
            }
            set
            {
                OnAreaCodeChanging(value);
                ReportPropertyChanging("AreaCode");
                _AreaCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaCode");
                OnAreaCodeChanged();
            }
        }
        private global::System.String _AreaCode;
        partial void OnAreaCodeChanging(global::System.String value);
        partial void OnAreaCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCashOnDelivery
        {
            get
            {
                return _IsCashOnDelivery;
            }
            set
            {
                OnIsCashOnDeliveryChanging(value);
                ReportPropertyChanging("IsCashOnDelivery");
                _IsCashOnDelivery = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCashOnDelivery");
                OnIsCashOnDeliveryChanged();
            }
        }
        private global::System.Boolean _IsCashOnDelivery;
        partial void OnIsCashOnDeliveryChanging(global::System.Boolean value);
        partial void OnIsCashOnDeliveryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private global::System.Boolean _IsEnable;
        partial void OnIsEnableChanging(global::System.Boolean value);
        partial void OnIsEnableChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DisplayOrder
        {
            get
            {
                return _DisplayOrder;
            }
            set
            {
                OnDisplayOrderChanging(value);
                ReportPropertyChanging("DisplayOrder");
                _DisplayOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisplayOrder");
                OnDisplayOrderChanged();
            }
        }
        private global::System.Int32 _DisplayOrder;
        partial void OnDisplayOrderChanging(global::System.Int32 value);
        partial void OnDisplayOrderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdateTime
        {
            get
            {
                return _LastUpdateTime;
            }
            set
            {
                OnLastUpdateTimeChanging(value);
                ReportPropertyChanging("LastUpdateTime");
                _LastUpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateTime");
                OnLastUpdateTimeChanged();
            }
        }
        private global::System.DateTime _LastUpdateTime;
        partial void OnLastUpdateTimeChanging(global::System.DateTime value);
        partial void OnLastUpdateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
