//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsInfo()
        {
            this.GoodsInfo_Attr = new HashSet<GoodsInfo_Attr>();
            this.GoodsInfo_Picture = new HashSet<GoodsInfo_Picture>();
            this.GoodsInfoSku = new HashSet<GoodsInfoSku>();
            this.GoodsInfoSku_Spec = new HashSet<GoodsInfoSku_Spec>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsName { get; set; }
        public string GoodsAlias { get; set; }
        public string GoodsUnit { get; set; }
        public string GoodsPlace { get; set; }
        public string GoodsNote { get; set; }
        public string GoodsDesc { get; set; }
        public string GoodsPic { get; set; }
        public string GoodsDetail { get; set; }
        public string GoodsDetailByWap { get; set; }
        public string KeyTitle { get; set; }
        public string KeyWords { get; set; }
        public string KeyDecription { get; set; }
        public bool IsIntegral { get; set; }
        public bool IsHot { get; set; }
        public bool IsNew { get; set; }
        public bool IsMoreSpec { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public Nullable<int> CompositeTotal { get; set; }
        public Nullable<int> OutwardTotal { get; set; }
        public Nullable<int> HealthyTotal { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public Nullable<int> PresaleId { get; set; }
        public bool IsCustomize { get; set; }
        public Nullable<int> CustomizeModelId { get; set; }
        public string CustomizeDfItem { get; set; }
        public string CustomizeOtherData { get; set; }
        public Nullable<int> Minimum { get; set; }
        public Nullable<int> Maximum { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfo_Attr> GoodsInfo_Attr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfo_Picture> GoodsInfo_Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfoSku> GoodsInfoSku { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfoSku_Spec> GoodsInfoSku_Spec { get; set; }
    }
}
