//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsAttr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsAttr()
        {
            this.GoodsInfo_Attr = new HashSet<GoodsInfo_Attr>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public string AttrName { get; set; }
        public string AttrValue { get; set; }
        public int ViewType { get; set; }
        public bool IsIntro { get; set; }
        public bool IsFilter { get; set; }
        public bool IsEnable { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual GoodsType GoodsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfo_Attr> GoodsInfo_Attr { get; set; }
    }
}
