//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfoSku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsInfoSku()
        {
            this.GoodsInfoSku_Spec = new HashSet<GoodsInfoSku_Spec>();
        }
    
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsName { get; set; }
        public string SpecName { get; set; }
        public string SpecNamePlex { get; set; }
        public string SpecDetail { get; set; }
        public string SkuNo { get; set; }
        public string BarCode { get; set; }
        public decimal Weight { get; set; }
        public decimal MarketPrice { get; set; }
        public decimal SalePrice { get; set; }
        public int ActualStock { get; set; }
        public int AllocateStock { get; set; }
        public int BadStock { get; set; }
        public int VirtualStock { get; set; }
        public Nullable<System.DateTime> WmsSyncLastTime { get; set; }
        public bool IsListShow { get; set; }
        public bool IsOffline { get; set; }
        public bool IsOutSale { get; set; }
        public string OutSale { get; set; }
        public bool IsSoldOut { get; set; }
        public bool IsHide { get; set; }
        public Nullable<int> ClickCount { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public string PictureIds { get; set; }
        public string DefaultPic { get; set; }
        public Nullable<decimal> ActPrice { get; set; }
        public string ActName { get; set; }
        public Nullable<System.DateTime> ActBeginTime { get; set; }
        public Nullable<System.DateTime> ActEndTime { get; set; }
        public Nullable<int> Minimum { get; set; }
        public Nullable<int> Maximum { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
    
        public virtual GoodsInfo GoodsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfoSku_Spec> GoodsInfoSku_Spec { get; set; }
    }
}
