//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsCategoryRelData
    {
        public int id { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string ImageUrl { get; set; }
        public string LinkUrl { get; set; }
        public string LinkTarget { get; set; }
        public int ItemType { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
