//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfigAll> ConfigAll { get; set; }
        public virtual DbSet<ConfigArea> ConfigArea { get; set; }
        public virtual DbSet<ConfigDeliveryArea> ConfigDeliveryArea { get; set; }
        public virtual DbSet<ConfigDeliveryAreaList> ConfigDeliveryAreaList { get; set; }
        public virtual DbSet<ConfigDeliveryWay> ConfigDeliveryWay { get; set; }
        public virtual DbSet<ConfigFiles> ConfigFiles { get; set; }
        public virtual DbSet<ConfigLogisticsCompany> ConfigLogisticsCompany { get; set; }
        public virtual DbSet<ConfigMsgTag> ConfigMsgTag { get; set; }
        public virtual DbSet<ConfigMsgTemplate> ConfigMsgTemplate { get; set; }
        public virtual DbSet<ConfigOAuthLogin> ConfigOAuthLogin { get; set; }
        public virtual DbSet<ConfigPayWay> ConfigPayWay { get; set; }
        public virtual DbSet<ConfigSms> ConfigSms { get; set; }
        public virtual DbSet<CustomizeElement> CustomizeElement { get; set; }
        public virtual DbSet<CustomizeEmbroidery> CustomizeEmbroidery { get; set; }
        public virtual DbSet<CustomizeItem> CustomizeItem { get; set; }
        public virtual DbSet<CustomizeModel> CustomizeModel { get; set; }
        public virtual DbSet<CustomizeStyle> CustomizeStyle { get; set; }
        public virtual DbSet<CustomizeStyleItem> CustomizeStyleItem { get; set; }
        public virtual DbSet<CustomizeUserInfo> CustomizeUserInfo { get; set; }
        public virtual DbSet<FabricStockLog> FabricStockLog { get; set; }
        public virtual DbSet<GoodsAttr> GoodsAttr { get; set; }
        public virtual DbSet<GoodsBrand> GoodsBrand { get; set; }
        public virtual DbSet<GoodsCategory> GoodsCategory { get; set; }
        public virtual DbSet<GoodsCategoryRelData> GoodsCategoryRelData { get; set; }
        public virtual DbSet<GoodsContainer> GoodsContainer { get; set; }
        public virtual DbSet<GoodsInfo> GoodsInfo { get; set; }
        public virtual DbSet<GoodsInfo_Attr> GoodsInfo_Attr { get; set; }
        public virtual DbSet<GoodsInfo_Picture> GoodsInfo_Picture { get; set; }
        public virtual DbSet<GoodsInfoSku> GoodsInfoSku { get; set; }
        public virtual DbSet<GoodsInfoSku_Spec> GoodsInfoSku_Spec { get; set; }
        public virtual DbSet<GoodsRelated> GoodsRelated { get; set; }
        public virtual DbSet<GoodsSkuAutoTask> GoodsSkuAutoTask { get; set; }
        public virtual DbSet<GoodsSpec> GoodsSpec { get; set; }
        public virtual DbSet<GoodsSpecValue> GoodsSpecValue { get; set; }
        public virtual DbSet<GoodsStockImport> GoodsStockImport { get; set; }
        public virtual DbSet<GoodsStockImportDetail> GoodsStockImportDetail { get; set; }
        public virtual DbSet<GoodsStockLog> GoodsStockLog { get; set; }
        public virtual DbSet<GoodsType> GoodsType { get; set; }
        public virtual DbSet<GoodsType_Brand> GoodsType_Brand { get; set; }
        public virtual DbSet<GoodsType_Spec> GoodsType_Spec { get; set; }
        public virtual DbSet<OrderGoods> OrderGoods { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<OrderLog> OrderLog { get; set; }
        public virtual DbSet<OrderLogisticsState> OrderLogisticsState { get; set; }
        public virtual DbSet<OrderPresaleItem> OrderPresaleItem { get; set; }
        public virtual DbSet<OutsideAd> OutsideAd { get; set; }
        public virtual DbSet<OutsideSite> OutsideSite { get; set; }
        public virtual DbSet<OutsideVisitLog> OutsideVisitLog { get; set; }
        public virtual DbSet<ReceiptDelivery> ReceiptDelivery { get; set; }
        public virtual DbSet<ReceiptReceive> ReceiptReceive { get; set; }
        public virtual DbSet<ReceiptRefund> ReceiptRefund { get; set; }
        public virtual DbSet<ReceiptReturn> ReceiptReturn { get; set; }
        public virtual DbSet<SalePresale> SalePresale { get; set; }
        public virtual DbSet<SalePresaleItem> SalePresaleItem { get; set; }
        public virtual DbSet<SaleRegGive> SaleRegGive { get; set; }
        public virtual DbSet<SaleRegGiveItem> SaleRegGiveItem { get; set; }
        public virtual DbSet<SalesActivity> SalesActivity { get; set; }
        public virtual DbSet<SalesActivityGift> SalesActivityGift { get; set; }
        public virtual DbSet<SalesActivityRange> SalesActivityRange { get; set; }
        public virtual DbSet<SalesActivityRule> SalesActivityRule { get; set; }
        public virtual DbSet<SalesActivityUserLevel> SalesActivityUserLevel { get; set; }
        public virtual DbSet<SalesCoupon> SalesCoupon { get; set; }
        public virtual DbSet<SalesCouponLog> SalesCouponLog { get; set; }
        public virtual DbSet<SalesCouponRange> SalesCouponRange { get; set; }
        public virtual DbSet<SalesCouponUserLevel> SalesCouponUserLevel { get; set; }
        public virtual DbSet<SevenDay> SevenDay { get; set; }
        public virtual DbSet<SevenDayCoupon> SevenDayCoupon { get; set; }
        public virtual DbSet<SevenDayCouponLog> SevenDayCouponLog { get; set; }
        public virtual DbSet<SevenDayProject> SevenDayProject { get; set; }
        public virtual DbSet<SiteTracksLog> SiteTracksLog { get; set; }
        public virtual DbSet<SiteWidget> SiteWidget { get; set; }
        public virtual DbSet<SupplyInvoice> SupplyInvoice { get; set; }
        public virtual DbSet<SupportCategory> SupportCategory { get; set; }
        public virtual DbSet<SupportDetail> SupportDetail { get; set; }
        public virtual DbSet<SupportInfo> SupportInfo { get; set; }
        public virtual DbSet<SupportLog> SupportLog { get; set; }
        public virtual DbSet<SupportRefund> SupportRefund { get; set; }
        public virtual DbSet<SupportService> SupportService { get; set; }
        public virtual DbSet<SysAdmin> SysAdmin { get; set; }
        public virtual DbSet<SysAdmin_Role> SysAdmin_Role { get; set; }
        public virtual DbSet<SysAdminLog> SysAdminLog { get; set; }
        public virtual DbSet<SysAdminPrivilege> SysAdminPrivilege { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SysModule> SysModule { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRole_Module> SysRole_Module { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<UserApprove> UserApprove { get; set; }
        public virtual DbSet<UserBalanceLog> UserBalanceLog { get; set; }
        public virtual DbSet<UserComment> UserComment { get; set; }
        public virtual DbSet<UserCommentItem> UserCommentItem { get; set; }
        public virtual DbSet<UserCoupon> UserCoupon { get; set; }
        public virtual DbSet<UserFavorites> UserFavorites { get; set; }
        public virtual DbSet<UserGift> UserGift { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserIntegralLog> UserIntegralLog { get; set; }
        public virtual DbSet<UserLevel> UserLevel { get; set; }
        public virtual DbSet<UserLiftLevelLog> UserLiftLevelLog { get; set; }
        public virtual DbSet<UserOAuth> UserOAuth { get; set; }
        public virtual DbSet<UserSendCouponLog> UserSendCouponLog { get; set; }
        public virtual DbSet<UserSignCalendar> UserSignCalendar { get; set; }
    }
}
