//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLogisticsState
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OrderCode { get; set; }
        public string ExpressName { get; set; }
        public string LogisticsNo { get; set; }
        public Nullable<int> ApiType { get; set; }
        public Nullable<int> ShowType { get; set; }
        public string ExpressDetail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Message { get; set; }
        public Nullable<int> IsCheck { get; set; }
        public string Status { get; set; }
        public string State { get; set; }
        public string Condition { get; set; }
    }
}
