//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderGoods
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public int PromotionId { get; set; }
        public string PromotionName { get; set; }
        public string PromotionMark { get; set; }
        public Nullable<int> CustomizeModelId { get; set; }
        public Nullable<int> CustomizeItemId { get; set; }
        public int ItemType { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public int GoodsId { get; set; }
        public int SkuId { get; set; }
        public int GoodsType { get; set; }
        public string GoodsNo { get; set; }
        public string BarCode { get; set; }
        public string SkuNo { get; set; }
        public string GoodsName { get; set; }
        public string GoodsSpec { get; set; }
        public string SpecNamePlex { get; set; }
        public string GoodsPic { get; set; }
        public int Quantity { get; set; }
        public decimal CostPrice { get; set; }
        public decimal MarketPrice { get; set; }
        public decimal SalePrice { get; set; }
        public decimal ActualPrice { get; set; }
        public decimal IntegralPrice { get; set; }
        public decimal CouponPrice { get; set; }
        public decimal BalancePrice { get; set; }
        public decimal OffPrice { get; set; }
        public int ReturnQuantity { get; set; }
        public Nullable<bool> IsComment { get; set; }
        public Nullable<bool> IsShare { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<int> SupportServiceId { get; set; }
        public Nullable<int> ConverState { get; set; }
        public Nullable<System.DateTime> ConverTime { get; set; }
        public Nullable<int> ProduceState { get; set; }
        public Nullable<System.DateTime> ProduceStateTime { get; set; }
    
        public virtual OrderInfo OrderInfo { get; set; }
    }
}
