//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideAd
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string AdName { get; set; }
        public string AdLink { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Days { get; set; }
        public int ClickNum { get; set; }
        public int RegNum { get; set; }
        public int BuyNum { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual OutsideSite OutsideSite { get; set; }
    }
}
