//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePresale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalePresale()
        {
            this.SalePresaleItem = new HashSet<SalePresaleItem>();
        }
    
        public int Id { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsName { get; set; }
        public int PresaleType { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime LastPayTime { get; set; }
        public bool IsFreeShipping { get; set; }
        public Nullable<bool> IsExecutePayTask { get; set; }
        public Nullable<System.DateTime> ExecutePayTaskTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalePresaleItem> SalePresaleItem { get; set; }
    }
}
