//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesActivityRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesActivityRule()
        {
            this.SalesActivityGift = new HashSet<SalesActivityGift>();
        }
    
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public decimal RangeAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public bool IsSpreeFixedAmount { get; set; }
        public Nullable<int> GiftMaxNum { get; set; }
        public int IntegralMultiple { get; set; }
        public int CouponId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesActivityGift> SalesActivityGift { get; set; }
    }
}
