//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePresaleItem
    {
        public int Id { get; set; }
        public int PresaleId { get; set; }
        public int SkuId { get; set; }
        public string SkuNo { get; set; }
        public string SpecName { get; set; }
        public int PresalePerson1 { get; set; }
        public decimal PresalePrice1 { get; set; }
        public int PresalePerson2 { get; set; }
        public decimal PresalePrice2 { get; set; }
        public int PresalePerson3 { get; set; }
        public decimal PresalePrice3 { get; set; }
        public decimal EarnestPrice { get; set; }
        public int UserMaxBuyNum { get; set; }
        public int MaxBuyNum { get; set; }
        public int BuyCount { get; set; }
    
        public virtual SalePresale SalePresale { get; set; }
    }
}
