//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesActivity()
        {
            this.SalesActivityGift = new HashSet<SalesActivityGift>();
            this.SalesActivityRange = new HashSet<SalesActivityRange>();
            this.SalesActivityUserLevel = new HashSet<SalesActivityUserLevel>();
        }
    
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public int ActivityType { get; set; }
        public Nullable<int> GiftType { get; set; }
        public bool IsGeometric { get; set; }
        public bool IsCoupon { get; set; }
        public int PrivilegeTerm { get; set; }
        public int PrivilegeWay { get; set; }
        public string SpreeRule { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Remarks { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesActivityGift> SalesActivityGift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesActivityRange> SalesActivityRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesActivityUserLevel> SalesActivityUserLevel { get; set; }
    }
}
