//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SevenDayCouponLog
    {
        public int Id { get; set; }
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string BuyProduct { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual SevenDayCoupon SevenDayCoupon { get; set; }
    }
}
