//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteTracksLog
    {
        public int Id { get; set; }
        public string VisitToken { get; set; }
        public int UserId { get; set; }
        public string Referer { get; set; }
        public string ClientAgent { get; set; }
        public int ActionType { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string PageUrl { get; set; }
        public string PageTitle { get; set; }
        public string Ip { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
