//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteWidget
    {
        public int Id { get; set; }
        public string WidgetSite { get; set; }
        public string WidgetPage { get; set; }
        public string SystemName { get; set; }
        public string WidgetName { get; set; }
        public string Description { get; set; }
        public bool IsEnable { get; set; }
        public string Data { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
