//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportService
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public string SkuNo { get; set; }
        public string TureName { get; set; }
        public string ProductCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string ReturnReasons { get; set; }
        public string B2CDiagnose { get; set; }
        public string SizeDiagnose { get; set; }
        public string WorkShopDiagnose { get; set; }
        public string AlterIdea { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
