//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportInfo()
        {
            this.SupportDetail = new HashSet<SupportDetail>();
        }
    
        public int Id { get; set; }
        public string SupportCode { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public decimal ReturnFreight { get; set; }
        public int RefundWay { get; set; }
        public string BankName { get; set; }
        public string BankUserName { get; set; }
        public string BankAccount { get; set; }
        public string ExpressName { get; set; }
        public string ExpressCode { get; set; }
        public int OrderPayWay { get; set; }
        public decimal Diffprice { get; set; }
        public string Consignee { get; set; }
        public string Sex { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public string DeliveryTime { get; set; }
        public string Remark { get; set; }
        public string OperUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<bool> IsPush { get; set; }
        public Nullable<System.DateTime> PushTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportDetail> SupportDetail { get; set; }
    }
}
