//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportRefund
    {
        public int Id { get; set; }
        public string RefundCode { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> SupportId { get; set; }
        public string SupportCode { get; set; }
        public int RefundType { get; set; }
        public int RefundState { get; set; }
        public decimal RefundAmount { get; set; }
        public int RefundWay { get; set; }
        public string RefundNumber { get; set; }
        public string BankName { get; set; }
        public string BankUserName { get; set; }
        public string BankAccount { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string AuditRemark { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> RefundTime { get; set; }
        public string RefundRemark { get; set; }
        public string RefundUser { get; set; }
        public string OperUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    }
}
