//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportDetail
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int SupportId { get; set; }
        public string SupportCode { get; set; }
        public int SupportType { get; set; }
        public int SupportState { get; set; }
        public Nullable<int> ReturnSource { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public int OrderGoodsId { get; set; }
        public int OrderGoodsNum { get; set; }
        public string OrderGoodsName { get; set; }
        public string OrderGoodsSkuNo { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal ReturnUserBalance { get; set; }
        public string ReturnCardCode { get; set; }
        public decimal ReturnCardPrice { get; set; }
        public decimal ReturnIntegral { get; set; }
        public Nullable<int> NewOrderGoodsId { get; set; }
        public Nullable<int> NewOrderGoodsNum { get; set; }
        public string NewGoodsName { get; set; }
        public string NewOrderGoodsSkuNo { get; set; }
        public int NewOrderId { get; set; }
        public string NewOrderCode { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CouponId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<decimal> CouponAmount { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string AuditRemark { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string CheckRemark { get; set; }
        public string CheckUser { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual SupportInfo SupportInfo { get; set; }
    }
}
