//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> SkuId { get; set; }
        public string GoodsName { get; set; }
        public string GoodsPic { get; set; }
        public Nullable<int> GoodsCategoryId { get; set; }
        public int Type { get; set; }
        public Nullable<int> FAQId { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public bool IsShare { get; set; }
        public string SharePicIds { get; set; }
        public bool IsAudit { get; set; }
        public bool IsAuditShare { get; set; }
        public bool IsView { get; set; }
        public bool IsReply { get; set; }
        public string ReplyContents { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public string Comefrom { get; set; }
        public Nullable<int> CompositeScore { get; set; }
        public Nullable<int> OutwardScore { get; set; }
        public Nullable<int> HealthyScore { get; set; }
        public Nullable<int> Integral { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UserNick { get; set; }
        public string UserAvatar { get; set; }
    }
}
