//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLiftLevelLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OldLevelId { get; set; }
        public int NewLevelId { get; set; }
        public bool IsUpgrade { get; set; }
        public bool IsHandleCoupon { get; set; }
        public string Remark { get; set; }
        public string OperUser { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
