//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApprove
    {
        public int Id { get; set; }
        public int ApproveType { get; set; }
        public int UserId { get; set; }
        public string ApproveKey { get; set; }
        public bool IsValidateKey { get; set; }
        public string ApproveMobile { get; set; }
        public string ApproveCode { get; set; }
        public Nullable<int> ApproveMobileCount { get; set; }
        public Nullable<System.DateTime> SendMobileTime { get; set; }
        public string ApproveEmail { get; set; }
        public string ApproveEmailCode { get; set; }
        public Nullable<int> ApproveEmailCount { get; set; }
        public Nullable<System.DateTime> SendEmailTime { get; set; }
        public Nullable<System.DateTime> LastUpdataTime { get; set; }
    }
}
