//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBalanceLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderCode { get; set; }
        public int BalanceType { get; set; }
        public int ActionType { get; set; }
        public decimal OldBalance { get; set; }
        public decimal Balance { get; set; }
        public decimal NewBalance { get; set; }
        public string Source { get; set; }
        public string Remarks { get; set; }
        public bool IsView { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
