//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.UserOAuth = new HashSet<UserOAuth>();
        }
    
        public int Id { get; set; }
        public int LevelId { get; set; }
        public int UserAccountId { get; set; }
        public int Type { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string TrueName { get; set; }
        public string NickName { get; set; }
        public string UserAvatar { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Waist { get; set; }
        public Nullable<bool> IsReceiveMsg { get; set; }
        public bool IsBlackUser { get; set; }
        public int LoginCount { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserLevel UserLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOAuth> UserOAuth { get; set; }
    }
}
