//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOAuth
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public Nullable<int> UserId { get; set; }
        public int OauthType { get; set; }
        public string OAuthUserId { get; set; }
        public string NickName { get; set; }
        public string UserPic { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
