//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int Id { get; set; }
        public decimal Integral { get; set; }
        public Nullable<decimal> IntegralLastUse { get; set; }
        public Nullable<System.DateTime> IntegralLastUseTime { get; set; }
        public decimal Balancel { get; set; }
        public Nullable<decimal> BalancelLastUse { get; set; }
        public Nullable<System.DateTime> BalancelLastUseTime { get; set; }
        public bool MobileIsValid { get; set; }
        public Nullable<System.DateTime> MobileValidTime { get; set; }
        public bool EmailIsValid { get; set; }
        public Nullable<System.DateTime> EmailValidTime { get; set; }
        public string PayPwd { get; set; }
        public Nullable<System.DateTime> PayPwdLastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
